# Generated by Django 2.1.5 on 2019-02-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=512)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=128)),
                ('completed', models.BooleanField(default=False)),
                ('data_bool', models.BooleanField(default=False)),
                ('data_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('data_date', models.DateField(blank=True, null=True)),
                ('data_file', models.FileField(blank=True, max_length=512, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('data_string', models.TextField(default='')),
                ('data_integer', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_submitted', models.DateTimeField(blank=True, null=True, verbose_name='date submitted')),
                ('submitted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_submit', models.BooleanField()),
                ('required', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('title', models.CharField(max_length=256)),
                ('html_description', models.TextField()),
                ('number', models.IntegerField()),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Report')),
            ],
        ),
    ]
