# Generated by Django 2.1.7 on 2019-03-03 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(default='field', max_length=512)),
                ('label', models.CharField(max_length=512)),
                ('number', models.IntegerField(default=0)),
                ('field_type', models.CharField(max_length=128)),
                ('completed', models.BooleanField(default=False)),
                ('data_bool', models.BooleanField(default=False)),
                ('data_decimal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('data_date', models.DateField(blank=True, null=True)),
                ('data_file', models.FileField(blank=True, max_length=512, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('data_string', models.TextField(blank=True, default='')),
                ('data_integer', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(default=datetime.date.today, verbose_name='date created')),
                ('date_submitted', models.DateTimeField(default=datetime.date.today, verbose_name='date submitted')),
                ('submitted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_submit', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('html_description', models.TextField()),
                ('number', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Report')),
            ],
        ),
    ]
