# Generated by Django 2.1.5 on 2019-02-01 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190131_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='field',
            name='data_integer',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='field',
            name='data_string',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='date submitted'),
        ),
    ]
