# Generated by Django 2.1.7 on 2019-03-08 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190308_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_submitted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submitted'),
        ),
    ]
