# Generated by Django 2.1.5 on 2019-01-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190125_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
