# Generated by Django 2.1.5 on 2019-02-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190131_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_name',
            field=models.CharField(default='field', max_length=512),
        ),
    ]
