# Generated by Django 2.1.5 on 2019-02-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_field_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
