# Generated by Django 2.1.5 on 2019-02-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190213_1719'),
        ('backend', '0006_auto_20190213_2113'),
    ]

    operations = [
    ]
