# Generated by Django 2.1.7 on 2019-03-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190214_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
